repos:
- repo: https://github.com/psf/black
  rev: 22.6.0
  hooks:
  - id: black

-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v1.1.1
    hooks:
    -   id: trailing-whitespace
        exclude: cherrypy/test/static/index.html
    -   id: flake8
    -   id: check-merge-conflict
    -   id: double-quote-string-fixer
        exclude: docs/conf.py
    -   id: end-of-file-fixer
    -   id: name-tests-test
        include: cherrypy/test/
        args:
        - --django
        exclude: tests/dist-check.py
    -   id: debug-statements
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-byte-order-marker
    -   id: check-case-conflict
    # disabled due to pre-commit/pre-commit-hooks#159
    #-   id: check-docstring-first
    -   id: check-json
        include: .mention-bot
    -   id: check-symlinks
    -   id: check-yaml
    -   id: detect-private-key
        exclude: cherrypy/test/test.pem
    -   id: requirements-txt-fixer

-   repo: https://github.com/Lucas-C/pre-commit-hooks-lxml.git
    rev: v1.1.0
    hooks:
    -   id: forbid-html-img-without-alt-text
