[build-system]
requires = [
    # Essentials
    "setuptools >= 45, < 60.9.0",  # The first version with setuptools-scm problems

    # Plugins
    "setuptools_scm[toml] >= 3.5",
    "setuptools_scm_git_archive >= 1.1",
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
